### ISSUE TITLE
Loving Ganesha - 2019 color edition needs to be turned in to a PWA

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/epub2pwa#11]
New book needs to turn in Progressive Web App.

/home/devhap/media/book/loving-ganesha

All new files

**Comment by Brahmanathaswami** [comment]
![2020-02-17_16-08-55](https://user-images.githubusercontent.com/3675722/74697849-00e75800-51a0-11ea-95f9-7c775e698667.png)

**Comment by soapdog** [comment]
"Loving Gaṇeśa: Hinduism’s Endearing Elephant-Faced God" is done but I think there is a mistake in the epub file. There is a placeholder page in it soon after the cover, check it out:

https://dev.himalayanacademy.com/media/books/loving-ganesha/web/

**Comment by soapdog** [comment]
"Hinduism, the Greatest Religion in the World"

https://dev.himalayanacademy.com/media/books/hinduism-the-greatest-religion_ei/web/

**Comment by soapdog** [comment]
"South India’s Bhakti Saints"

https://dev.himalayanacademy.com/media/books/south-india-bhakti-saints_ei/web/

**Comment by soapdog** [comment]
"Hinduism in a Nutshell"

https://dev.himalayanacademy.com/media/books/hinduism-in-a-nutshell_ei/web/

**Comment by soapdog** [comment]
"The Rasas"

https://dev.himalayanacademy.com/media/books/rasas-nine-emotions_ei/web

**Comment by soapdog** [comment]
Awaiting approval.

**Comment by Brahmanathaswami** [comment]
I trust you ... test in one carefully, move to production, close the issue yourself.

**Comment by soapdog** [comment]
@Brahmanathaswami please check the bug I mentioned in Loving Ganesha.

**Comment by Brahmanathaswami** [comment]
Argh... we should not use those place holder! even for print production. 

I will have Atrtex re-do it. I suppose you can't simply remove the *.html from the epub because it will break the spine..... so we have wait...

**Comment by Brahmanathaswami** [comment]
A new .epub, .mobi, pdf have been uploaded this is back on the roster

**Comment by soapdog** [comment]
fixed.
