### ISSUE TITLE
Process Evernew, Evernow

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/epub2pwa#4]
I went ahead and create to record and install the books and cover.

HAPMAN/Books/Item ID 8933

All you have to do 
- its process the book, 
 - test it, 
 - turn on "Approved for Public" :YES  in HAPMAN
 - and sync with www.himalayanacademy.com

**Comment by soapdog** [comment]
working on it

**Comment by soapdog** [comment]
book exported to: dev.himalayanacademy.com/media/books/evernew-evernow/web

Noticed that the web reader links are wrong in our HAP app on devhap. Will fix them.

**Comment by soapdog** [comment]
altered views and scripts on devhap

**Comment by soapdog** [comment]
book available in: https://www.himalayanacademy.com/media/books/evernew-evernow/web/

Be aware that this book **has no table of contents**.
