### ISSUE TITLE
Guru's Wisdom book

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/epub2pwa#6]
This book has been uploaded to HAPMAN.  I have yet to add the PDF (has come from Atritex)

 [ ]  Process to PWA and copy to mainsite.
 [ ] Confirm and if OK Approved for Public : YES

**Comment by soapdog** [comment]
Done.

https://www.himalayanacademy.com/view/gurus-wisdom

and the book content

https://www.himalayanacademy.com/media/books/gurus-wisdom/web/
